builds:
  teamcity:
    - id: "VertisAdmin_Hub_Build"
      path: "*"
      properties:
        - name: "prop"
          value: "val"
    - id: "VertisAdmin_HprofIntermediary_HprofIntermediary"
      path: "*"
